version: '3.8'

services:
  es:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - ES_ENDPOINT_STRATEGY=path
      ports:
      - "9200:9200"
      - "9300:9300"

  web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/usr/src/app/
      ports:
        - 8000:8000
      env_file:
        - docker-compose.env
      depends_on:
        - es